export type Role = "Administrator" | "Security Officer" | "Analyst" | "Staff" | "Student";
export type Severity = "Critical" | "High" | "Moderate" | "Low";
export type IncidentStatus = "Open" | "Investigating" | "Escalated" | "Resolved" | "Closed";
export type AlertStatus = "Active" | "Acknowledged" | "Dismissed" | "Resolved";

export interface Incident {
  id: string;
  type: string;
  description: string;
  location: string;
  severity: Severity;
  status: IncidentStatus;
  reporter: string;
  reporterEmail?: string;
  assigned: string;
  time: string;
  riskScore: number;
  evidence?: string;
  timeline: { time: string; action: string; by: string; note?: string }[];
  comments: { time: string; author: string; text: string }[];
}

export interface Alert {
  id: string;
  rule: string;
  incident: string;
  severity: Severity;
  time: string;
  status: AlertStatus;
  description: string;
  dismissReason?: string;
}

export interface AuditLog {
  id: string;
  user: string;
  action: string;
  entity: string;
  prev: string;
  next: string;
  time: string;
  hash: string;
  prevHash: string;
  ip: string;
}

export const LOCATIONS = [
  "Server Room — Block C",
  "IT Infrastructure Hub",
  "Parking Lot B — Zone 3",
  "Research Labs — Floor 5",
  "Chemistry Lab — Wing D",
  "Student Hostel A",
  "Cafeteria Block",
  "Gymnasium",
  "Admin Block — UPS Room",
  "Library — Wi-Fi Zone",
  "Main Gate",
  "Academic Block — Floor 2",
  "Sports Complex",
  "Auditorium",
  "Medical Center",
];

export const INCIDENT_TYPES = [
  "Unauthorized Access",
  "Suspicious Activity",
  "Network Security Alert",
  "Environmental Risk",
  "Emergency — Medical",
  "Infrastructure Failure",
  "Fire Alarm",
  "Theft / Property",
  "Physical Altercation",
  "Vehicle Incident",
];

export const mockUser = {
  name: "Dr. Priya Sharma",
  email: "p.sharma@campus.edu",
  role: "Administrator" as Role,
  avatar: "PS",
  lastLogin: "2026-09-13 08:41 UTC",
};

export const stats = {
  totalIncidents: 1284,
  openIncidents: 47,
  criticalIncidents: 12,
  resolvedToday: 23,
  avgResolutionHours: 4.2,
  riskScore: 68,
  anomaliesDetected: 8,
  activeAlerts: 15,
};

export const initialIncidents: Incident[] = [
  {
    id: "INC-2891", type: "Unauthorized Access", description: "Badge cloned — entry to server room at 07:20 without authorization. CCTV shows unidentified individual.",
    location: "Server Room — Block C", severity: "Critical", status: "Escalated",
    reporter: "Sgt. Rajan Mehta", reporterEmail: "r.mehta@campus.edu", assigned: "Lt. Kavita Nair", time: "2026-09-13 07:22", riskScore: 91, evidence: "CCTV-C4-07:20",
    timeline: [
      { time: "07:22", action: "Incident Created", by: "Sgt. R. Mehta" },
      { time: "07:24", action: "Assigned to Lt. K. Nair", by: "Dr. P. Sharma" },
      { time: "07:25", action: "Status → Escalated", by: "Dr. P. Sharma", note: "Unauthorized server access — immediate response" },
    ],
    comments: [{ time: "07:30", author: "Lt. K. Nair", text: "En route to server room, backup requested." }],
  },
  {
    id: "INC-2890", type: "Suspicious Activity", description: "Individual observed circling Parking Lot B perimeter for 45 minutes without vehicle. Refused to identify when approached.",
    location: "Parking Lot B — Zone 3", severity: "High", status: "Investigating",
    reporter: "CCTV Auto-Detect", assigned: "Off. Dev Patel", time: "2026-09-13 06:55", riskScore: 74,
    timeline: [
      { time: "06:55", action: "Auto-detected by CCTV AI", by: "System" },
      { time: "07:05", action: "Assigned to Off. D. Patel", by: "Lt. K. Nair" },
      { time: "07:07", action: "Status → Investigating", by: "Off. D. Patel" },
    ],
    comments: [],
  },
  {
    id: "INC-2889", type: "Network Security Alert", description: "Port scan detected from internal IP 10.4.8.44 — 2,400 SYN packets in 60 seconds targeting server subnet.",
    location: "IT Infrastructure Hub", severity: "Critical", status: "Open",
    reporter: "IDS System", assigned: "Unassigned", time: "2026-09-13 06:31", riskScore: 88,
    timeline: [{ time: "06:31", action: "Auto-generated by IDS", by: "System" }],
    comments: [],
  },
  {
    id: "INC-2888", type: "Environmental Risk", description: "Fume hood exhaust failure in Chemistry Lab D-4. CO₂ sensor reading elevated at 1,200 ppm.",
    location: "Chemistry Lab — Wing D", severity: "High", status: "Resolved",
    reporter: "Sensor Array D-4", assigned: "Dr. Meera Iyer", time: "2026-09-13 05:10", riskScore: 62,
    timeline: [
      { time: "05:10", action: "Sensor alert generated", by: "System" },
      { time: "05:18", action: "Assigned to Dr. M. Iyer", by: "Lt. K. Nair" },
      { time: "06:45", action: "Status → Resolved", by: "Dr. M. Iyer", note: "Exhaust repaired. CO₂ back to normal." },
    ],
    comments: [{ time: "05:25", author: "Dr. M. Iyer", text: "Lab evacuated, maintenance contacted." }],
  },
  {
    id: "INC-2887", type: "Emergency — Medical", description: "Student collapsed during basketball training. Suspected heat exhaustion.",
    location: "Gymnasium", severity: "Moderate", status: "Resolved",
    reporter: "Staff — Ankit Rao", reporterEmail: "a.rao@campus.edu", assigned: "Medical Unit 1", time: "2026-09-13 04:48", riskScore: 45,
    timeline: [
      { time: "04:48", action: "Incident Created", by: "A. Rao" },
      { time: "04:49", action: "Medical Unit dispatched", by: "System" },
      { time: "05:20", action: "Status → Resolved", by: "Medical Unit 1", note: "Student stable, transported to clinic." },
    ],
    comments: [],
  },
  {
    id: "INC-2886", type: "Infrastructure Failure", description: "UPS battery failure in Admin Block. Building on generator. Runtime approximately 4 hours.",
    location: "Admin Block — UPS Room", severity: "High", status: "Investigating",
    reporter: "SCADA Monitor", assigned: "Eng. Suresh Kumar", time: "2026-09-13 03:30", riskScore: 71,
    timeline: [
      { time: "03:30", action: "SCADA alert generated", by: "System" },
      { time: "03:45", action: "Assigned to Eng. S. Kumar", by: "Lt. K. Nair" },
    ],
    comments: [{ time: "03:50", author: "Eng. S. Kumar", text: "Replacement battery ordered. ETA 6h." }],
  },
  {
    id: "INC-2885", type: "Unauthorized Access", description: "Access card used after reported stolen. Lab accessed at 22:15 without authorization.",
    location: "Research Labs — Floor 5", severity: "Moderate", status: "Closed",
    reporter: "Access Control Sys", assigned: "Sgt. Rajan Mehta", time: "2026-09-12 22:15", riskScore: 38,
    timeline: [
      { time: "22:15", action: "Access Control alert", by: "System" },
      { time: "22:30", action: "Assigned to Sgt. R. Mehta", by: "Lt. K. Nair" },
      { time: "23:45", action: "Status → Closed", by: "Sgt. R. Mehta", note: "Card deactivated. Review completed." },
    ],
    comments: [],
  },
  {
    id: "INC-2884", type: "Fire Alarm", description: "Cafeteria fire sensor triggered by burnt food. Confirmed false alarm after visual inspection.",
    location: "Cafeteria Block", severity: "Low", status: "Closed",
    reporter: "Fire Sensor F-12", assigned: "Maint. Team B", time: "2026-09-12 21:00", riskScore: 18,
    timeline: [
      { time: "21:00", action: "Sensor triggered", by: "System" },
      { time: "21:08", action: "Status → Closed — False Alarm", by: "Maint. Team B" },
    ],
    comments: [],
  },
  {
    id: "INC-2883", type: "Network Security Alert", description: "Multiple failed WPA2 handshake attempts on Library Wi-Fi. Possible deauth attack.",
    location: "Library — Wi-Fi Zone", severity: "High", status: "Open",
    reporter: "IDS System", assigned: "Unassigned", time: "2026-09-12 20:44", riskScore: 79,
    timeline: [{ time: "20:44", action: "IDS alert generated", by: "System" }],
    comments: [],
  },
  {
    id: "INC-2882", type: "Suspicious Activity", description: "Unidentified individual attempting to enter hostel rooms on Floor 3 without key card.",
    location: "Student Hostel A", severity: "Moderate", status: "Investigating",
    reporter: "Guard — Balveer Singh", assigned: "Off. Neha Kapoor", time: "2026-09-12 19:30", riskScore: 52,
    timeline: [
      { time: "19:30", action: "Incident Created", by: "B. Singh" },
      { time: "19:40", action: "Assigned to Off. N. Kapoor", by: "Sgt. R. Mehta" },
    ],
    comments: [],
  },
];

export const trendData = [
  { date: "Sep 4", incidents: 18, critical: 2, resolved: 16 },
  { date: "Sep 5", incidents: 24, critical: 4, resolved: 19 },
  { date: "Sep 6", incidents: 15, critical: 1, resolved: 14 },
  { date: "Sep 7", incidents: 31, critical: 7, resolved: 22 },
  { date: "Sep 8", incidents: 27, critical: 5, resolved: 25 },
  { date: "Sep 9", incidents: 20, critical: 3, resolved: 18 },
  { date: "Sep 10", incidents: 35, critical: 8, resolved: 28 },
  { date: "Sep 11", incidents: 29, critical: 6, resolved: 24 },
  { date: "Sep 12", incidents: 42, critical: 10, resolved: 33 },
  { date: "Sep 13", incidents: 47, critical: 12, resolved: 23 },
];

export const incidentTypeData = [
  { name: "Unauthorized Access", value: 312, color: "#ef4444" },
  { name: "Network Security", value: 287, color: "#00d4ff" },
  { name: "Suspicious Activity", value: 241, color: "#f59e0b" },
  { name: "Infrastructure", value: 189, color: "#7c3aed" },
  { name: "Environmental", value: 143, color: "#10b981" },
  { name: "Emergency", value: 112, color: "#ec4899" },
];

export const locationRiskData = [
  { location: "Server Room — Block C", incidents: 87, riskScore: 91, trend: "+12%" },
  { location: "Parking Lot B", incidents: 64, riskScore: 74, trend: "+8%" },
  { location: "Research Labs — F5", incidents: 58, riskScore: 71, trend: "+5%" },
  { location: "IT Infrastructure Hub", incidents: 52, riskScore: 69, trend: "+18%" },
  { location: "Student Hostel A", incidents: 43, riskScore: 55, trend: "-3%" },
  { location: "Chemistry Lab D", incidents: 38, riskScore: 62, trend: "+2%" },
];

export const initialAlerts: Alert[] = [
  { id: "ALT-1041", rule: "Critical incident auto-escalation", incident: "INC-2891", severity: "Critical", time: "07:22", status: "Active", description: "Unauthorized server room access — immediate response required" },
  { id: "ALT-1040", rule: "Repeated location — elevated risk", incident: "INC-2889", severity: "Critical", time: "06:31", status: "Active", description: "3rd network intrusion attempt at IT Hub in 24h window" },
  { id: "ALT-1039", rule: "SLA exceeded — no assignment", incident: "INC-2883", severity: "High", time: "05:00", status: "Active", description: "Network alert unassigned for 15h — SLA breach at 4h" },
  { id: "ALT-1038", rule: "ML anomaly cluster detected", incident: "Multiple", severity: "High", time: "04:30", status: "Acknowledged", description: "Anomaly model flagged 4 correlated incidents overnight" },
  { id: "ALT-1037", rule: "High-risk zone monitoring", incident: "INC-2886", severity: "Moderate", time: "03:30", status: "Acknowledged", description: "UPS failure in Admin Block — power continuity at risk" },
  { id: "ALT-1036", rule: "Repeated location — elevated risk", incident: "INC-2890", severity: "High", time: "06:55", status: "Active", description: "5th suspicious activity in Parking Lot B this week" },
  { id: "ALT-1035", rule: "SLA breach warning", incident: "INC-2888", severity: "Low", time: "Yesterday", status: "Resolved", description: "Environmental alert resolved — SLA met within 6h" },
];

export const mlInsights = [
  { type: "Anomaly Detected", location: "IT Infrastructure Hub", confidence: 94, detail: "Unusual port-scan pattern — 3 AM activity spike inconsistent with baseline", flagged: "2026-09-13 03:12", model: "Isolation Forest",
    shap: [{ feature: "Time of Day", value: 34 }, { feature: "Location History", value: 28 }, { feature: "Recurrence", value: 22 }, { feature: "Incident Type", value: 11 }, { feature: "Day of Week", value: 5 }] },
  { type: "High-Risk Prediction", location: "Server Room — Block C", confidence: 87, detail: "Access pattern analysis predicts unauthorized attempt within next 6h", flagged: "2026-09-13 05:00", model: "Random Forest",
    shap: [{ feature: "Location History", value: 38 }, { feature: "Time of Day", value: 25 }, { feature: "Severity Score", value: 18 }, { feature: "Day of Week", value: 12 }, { feature: "Recurrence", value: 7 }] },
  { type: "Trend Alert", location: "Parking Lot B", confidence: 79, detail: "Weekly incident frequency rising 8% — correlates with semester exam period", flagged: "2026-09-13 02:30", model: "Time-Series ARIMA",
    shap: [{ feature: "Historical Frequency", value: 41 }, { feature: "Day of Week", value: 27 }, { feature: "Time of Day", value: 18 }, { feature: "Location", value: 9 }, { feature: "Recurrence", value: 5 }] },
  { type: "Anomaly Detected", location: "Student Hostel A", confidence: 71, detail: "Access card cloning pattern detected — 3 distinct IDs sharing same badge", flagged: "2026-09-12 23:45", model: "Isolation Forest",
    shap: [{ feature: "Recurrence", value: 45 }, { feature: "Location History", value: 30 }, { feature: "Time of Day", value: 15 }, { feature: "Incident Type", value: 7 }, { feature: "Severity Score", value: 3 }] },
  { type: "Risk Cluster", location: "Research Labs — Floor 5", confidence: 68, detail: "Lab access during off-hours clustered to same individual — review needed", flagged: "2026-09-12 22:10", model: "XGBoost",
    shap: [{ feature: "Time of Day", value: 36 }, { feature: "Location", value: 29 }, { feature: "Recurrence", value: 20 }, { feature: "Historical Frequency", value: 10 }, { feature: "Day of Week", value: 5 }] },
];

export const initialAuditLogs: AuditLog[] = [
  { id: "AUD-9882", user: "p.sharma@campus.edu", action: "INCIDENT_ESCALATED", entity: "INC-2891", prev: "Investigating", next: "Escalated", time: "2026-09-13 07:25", hash: "a3f9d2c1", prevHash: "b7e1a4f3", ip: "10.4.1.22" },
  { id: "AUD-9881", user: "k.nair@campus.edu", action: "INCIDENT_ASSIGNED", entity: "INC-2891", prev: "Unassigned", next: "Lt. K. Nair", time: "2026-09-13 07:24", hash: "b7e1a4f3", prevHash: "c2d8f5a9", ip: "10.4.1.35" },
  { id: "AUD-9880", user: "system@sentinelx", action: "ALERT_GENERATED", entity: "ALT-1041", prev: "—", next: "Active", time: "2026-09-13 07:22", hash: "c2d8f5a9", prevHash: "d1a7b3e6", ip: "10.4.0.1" },
  { id: "AUD-9879", user: "r.mehta@campus.edu", action: "INCIDENT_CREATED", entity: "INC-2891", prev: "—", next: "Open", time: "2026-09-13 07:22", hash: "d1a7b3e6", prevHash: "e8c4f2b7", ip: "10.4.2.18" },
  { id: "AUD-9878", user: "ids-system@sentinelx", action: "INCIDENT_CREATED", entity: "INC-2889", prev: "—", next: "Open", time: "2026-09-13 06:31", hash: "e8c4f2b7", prevHash: "f3b9e1d4", ip: "10.4.0.3" },
  { id: "AUD-9877", user: "d.patel@campus.edu", action: "INCIDENT_STATUS_CHANGED", entity: "INC-2890", prev: "Open", next: "Investigating", time: "2026-09-13 07:05", hash: "f3b9e1d4", prevHash: "a9d2c7f1", ip: "10.4.3.44" },
  { id: "AUD-9876", user: "p.sharma@campus.edu", action: "USER_ROLE_MODIFIED", entity: "USR-0044", prev: "Analyst", next: "Security Officer", time: "2026-09-13 06:00", hash: "a9d2c7f1", prevHash: "b4e8a3c6", ip: "10.4.1.22" },
  { id: "AUD-9875", user: "system@sentinelx", action: "ML_PREDICTION_STORED", entity: "PRED-0291", prev: "—", next: "Score: 94%", time: "2026-09-13 05:15", hash: "b4e8a3c6", prevHash: "0000000", ip: "10.4.0.2" },
];

export const heatmapZones = [
  { id: 1, name: "Server Room — Block C", x: 72, y: 18, risk: 91, incidents: 87, type: "Critical",
    action: "Deploy 24/7 guard. Rotate access credentials immediately.",
    history: [82, 85, 88, 90, 87, 91, 89, 91], trend: "+5%" },
  { id: 2, name: "IT Infrastructure Hub", x: 58, y: 32, risk: 88, incidents: 52, type: "Critical",
    action: "Isolate affected network segment. Engage SOC for forensic analysis.",
    history: [70, 74, 78, 80, 82, 85, 87, 88], trend: "+18%" },
  { id: 3, name: "Parking Lot B", x: 25, y: 65, risk: 74, incidents: 64, type: "High",
    action: "Increase patrol frequency to every 2h. Install additional CCTV.",
    history: [60, 62, 65, 68, 70, 71, 73, 74], trend: "+8%" },
  { id: 4, name: "Research Labs — F5", x: 82, y: 45, risk: 71, incidents: 58, type: "High",
    action: "Review off-hours access logs. Enforce two-person access rule.",
    history: [65, 66, 68, 69, 70, 70, 71, 71], trend: "+5%" },
  { id: 5, name: "Chemistry Lab — Wing D", x: 45, y: 55, risk: 62, incidents: 38, type: "High",
    action: "Inspect sensor calibration. Verify fume hood maintenance schedule.",
    history: [50, 53, 55, 58, 59, 60, 61, 62], trend: "+2%" },
  { id: 6, name: "Student Hostel A", x: 15, y: 35, risk: 55, incidents: 43, type: "Moderate",
    action: "Brief resident wardens. Check access card audit logs.",
    history: [58, 57, 56, 55, 56, 57, 55, 55], trend: "-3%" },
  { id: 7, name: "Cafeteria Block", x: 50, y: 75, risk: 32, incidents: 22, type: "Moderate",
    action: "Standard monitoring. No immediate escalation required.",
    history: [30, 31, 32, 30, 31, 32, 32, 32], trend: "+0%" },
  { id: 8, name: "Gymnasium", x: 35, y: 82, risk: 28, incidents: 18, type: "Low",
    action: "Routine patrol. Ensure medical kit is stocked.",
    history: [28, 27, 29, 28, 27, 28, 29, 28], trend: "+0%" },
  { id: 9, name: "Admin Block — UPS Room", x: 62, y: 70, risk: 71, incidents: 31, type: "High",
    action: "Replace UPS battery. Test generator failover. Notify facilities.",
    history: [40, 45, 50, 55, 60, 65, 68, 71], trend: "+25%" },
  { id: 10, name: "Library — Wi-Fi Zone", x: 30, y: 50, risk: 48, incidents: 27, type: "Moderate",
    action: "Monitor Wi-Fi traffic. Consider RADIUS authentication enforcement.",
    history: [42, 44, 45, 46, 47, 48, 48, 48], trend: "+5%" },
];

export const users = [
  { id: "USR-0001", name: "Dr. Priya Sharma", email: "p.sharma@campus.edu", role: "Administrator", status: "Active", lastLogin: "Today 08:41", incidents: 0 },
  { id: "USR-0012", name: "Lt. Kavita Nair", email: "k.nair@campus.edu", role: "Security Officer", status: "Active", lastLogin: "Today 07:24", incidents: 23 },
  { id: "USR-0018", name: "Sgt. Rajan Mehta", email: "r.mehta@campus.edu", role: "Security Officer", status: "Active", lastLogin: "Today 07:22", incidents: 41 },
  { id: "USR-0025", name: "Off. Dev Patel", email: "d.patel@campus.edu", role: "Security Officer", status: "Active", lastLogin: "Today 07:05", incidents: 18 },
  { id: "USR-0033", name: "Dr. Meera Iyer", email: "m.iyer@campus.edu", role: "Analyst", status: "Active", lastLogin: "Yesterday", incidents: 0 },
  { id: "USR-0044", name: "Eng. Suresh Kumar", email: "s.kumar@campus.edu", role: "Security Officer", status: "Active", lastLogin: "Today 03:30", incidents: 12 },
  { id: "USR-0067", name: "Rohan Verma", email: "r.verma@campus.edu", role: "Staff", status: "Active", lastLogin: "Today 08:10", incidents: 3 },
  { id: "USR-0091", name: "Ananya Gupta", email: "a.gupta@campus.edu", role: "Student", status: "Active", lastLogin: "Today 09:00", incidents: 2 },
];

export const RANDOM_ALERT_TEMPLATES = [
  { rule: "Unusual access attempt", severity: "High" as Severity, desc: "Repeated failed badge swipes detected at restricted zone" },
  { rule: "Network anomaly spike", severity: "Critical" as Severity, desc: "Traffic volume 3× baseline on internal subnet — IDS flagged" },
  { rule: "Environmental sensor threshold", severity: "Moderate" as Severity, desc: "Temperature sensor in Server Room exceeded 28°C threshold" },
  { rule: "SLA breach warning", severity: "High" as Severity, desc: "Incident unresolved past SLA — escalation imminent" },
  { rule: "ML anomaly detected", severity: "Moderate" as Severity, desc: "Isolation Forest flagged off-pattern behavior in access logs" },
  { rule: "Perimeter alert", severity: "High" as Severity, desc: "Motion detected in restricted campus zone after hours" },
];
